version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.17.1
    environment:
        CI: "false"
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install --f
      - run:
          name: Install Firebase Dev
          command: npm install --save-dev firebase-tools@11.9.0
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: |
            if [ $CIRCLE_BRANCH = 'main' ]; then
              npm run build
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: ~/repo
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy 
          command: ./node_modules/.bin/firebase deploy --token=1//0gVWVT478X20pCgYIARAAGBASNwF-L9Irf8AyFP6OLKZN9KNrIPTpBiwWKdFq1SGCaBBsUNnSYTH1KgWnlSv2plWTPCksrRTwZic
          
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - dev
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - dev
                - main